# Make sure the config file are with all values and provide ways to rewrite them in the config file and CLI

default_config:
  repo_prefix: '/hydra'
  node_name: null
  data_storage_path: null
  global_view_path: null
  svs_storage_path: null
  logging_path: null
  loop_period: 5000
  tracker_rate: 25000
  heartbeat_rate: 20000
  beats_to_renew: 3
  beats_to_fail: 3
  replication_degree: 2
  file_expiration: 0 # in hours, 0 = never expire
  rtt: 0
  num_users: 0
  bandwidth: 0
  network_cost: 0
  storage_cost: 0
  remaining_storage: 0
